project_id = "volvxnnxnynqtlmfapvp"

[functions.ocr-extract]
verify_jwt = false

[functions.extract-profile-from-url]
verify_jwt = false

[functions.import-instagram-stories]
verify_jwt = false

[functions.chat-asistente]
verify_jwt = false