import { createContext, useContext, useState, ReactNode } from "react";

export type Lang = "es" | "en" | "fr" | "pt";

const langLabels: Record<Lang, string> = { es: "ES", en: "EN", fr: "FR", pt: "PT" };
const langFlags: Record<Lang, string> = { es: "🇦🇷", en: "🇬🇧", fr: "🇫🇷", pt: "🇧🇷" };

// ─── Translation keys ───
const translations: Record<Lang, Record<string, string>> = {
  es: {
    // Navbar
    "nav.home": "Inicio",
    "nav.map": "Mapa",
    "nav.market": "Mercado",
    "nav.actors": "Red",
    "nav.register": "Registrarse",
    "nav.login": "Ingresar",
    "nav.logout": "Salir",
    // Hero
    "hero.badge": "Trazabilidad · Certificación Participativa · Sistemas Alimentarios",
    "hero.title_1": "La red que conecta al ",
    "hero.title_highlight": "campo agroecológico",
    "hero.subtitle": "Mapa interactivo, marketplace y trazabilidad para productores, cooperativas, comedores, restaurantes y consumidores.",
    "hero.cta_map": "Explorar el Mapa",
    "hero.cta_market": "Accedé al Mercado Agroecológico",
    "hero.stat_producers": "Productores",
    "hero.stat_points": "Puntos de venta",
    "hero.stat_kitchens": "Comedores",
    "hero.stat_regions": "Regiones",
    // Features
    "features.badge": "Módulos de la plataforma",
    "features.title": "Infraestructura digital para sistemas alimentarios agroecológicos",
    "features.subtitle": "Cada módulo está diseñado para conectar actores, reducir intermediarios y fortalecer la soberanía alimentaria.",
    "features.map": "Mapa Agroecológico",
    "features.map_desc": "Mapa interactivo con productores, cooperativas, comedores y puntos de venta geolocalizados. Filtrá por tipo de actor, producto o certificación. Hacé clic en un marcador para ver datos y acceder al mercado.",
    "features.marketplace": "Mercado Agroecológico",
    "features.marketplace_desc": "Oferta y demanda de alimentos agroecológicos con matching automático por proximidad geográfica.",
    "features.cert": "Certificación Participativa (SPG)",
    "features.cert_desc": "Accedé a cómo funciona cada SPG, cuestionarios de evaluación, visitas de pares, niveles de certificación y validación comunitaria. Toda la información transparente.",
    "features.logistics": "Logística Inteligente",
    "features.logistics_desc": "Optimización de rutas, camiones disponibles, centros de acopio y capacidad de distribución compartida para reducir costos y huella ecológica.",
    "features.comm": "Red de Comunicación",
    "features.comm_desc": "Mensajería directa, grupos regionales y notificaciones de oferta y demanda en tiempo real.",
    "features.dashboard": "Dashboard Analítico",
    "features.dashboard_desc": "Métricas de impacto, planificación de producción, pronóstico de demanda e indicadores ambientales.",
    "features.scalable": "Modular y Escalable",
    "features.scalable_desc": "Nuevas regiones e instituciones pueden incorporarse fácilmente al ecosistema de la plataforma.",
    "features.services": "Servicios Integrales",
    "features.services_desc": "Bio-insumos, semillas, asistencia técnica, financiamiento, almacenamiento y logística. Todo para tu transición agroecológica.",
    // Actors section
    "actors_section.badge": "Ecosistema multi-actor",
    "actors_section.title": "Todos los actores del sistema alimentario, conectados",
    "actors_section.subtitle": "Desde el campo hasta la mesa, cada actor del sistema alimentario tiene su lugar en la red.",
    "actors_section.producers": "Productores Agroecológicos",
    "actors_section.cooperatives": "Cooperativas y Asociaciones",
    "actors_section.kitchens": "Comedores Comunitarios",
    "actors_section.schools": "Escuelas y Universidades",
    "actors_section.consumers": "Consumidores Individuales",
    "actors_section.restaurants": "Restaurantes y Bares",
    "actors_section.retail": "Comercios y Ferias",
    "actors_section.institutions": "Instituciones Públicas",
    "actors_section.logistics": "Proveedores Logísticos",
    "actors_section.processing": "Plantas de Procesamiento",
    // CTA
    "cta.badge": "Más de 1,200 actores ya forman parte",
    "cta.title": "Sumate a la red agroecológica",
    "cta.subtitle": "Ofrecé tus productos, encontrá lo que necesitás cerca tuyo y formá parte de una economía alimentaria más justa y sustentable.",
    "cta.register": "Registrarme ahora",
    "cta.explore": "Explorar el mapa",
    // Footer
    "footer.description": "Plataforma digital para el mapeo, conexión y comercialización de alimentos agroecológicos. Sistemas alimentarios sustentables, producción agroecológica, comercio justo.",
    "footer.platform": "Plataforma",
    "footer.interactive_map": "Mapa Interactivo",
    "footer.marketplace": "Marketplace",
    "footer.actor_network": "Miembros de la Red",
    "footer.register": "Registrarse",
    "footer.resources": "Recursos",
    "footer.api_docs": "Documentación API",
    "footer.participatory_cert": "Certificación Participativa",
    "footer.contact": "Contacto",
    "footer.copyright": "© 2026 AgroEco.Red. Soberanía alimentaria y agroecología.",
    "footer.tagline": "Hecho con 🌱 para la tierra",
    // Marketplace
    "market.title": "Mercado Agroecológico",
    "market.subtitle": "Productos frescos directamente de productores agroecológicos certificados. Sin intermediarios, con trazabilidad completa.",
    "market.search": "Buscar producto o productor...",
    "market.all": "Todos",
    "market.products_available": "productos disponibles",
    "market.clear_sort": "Limpiar orden",
    "market.contact": "Contactar",
    "market.in_season": "De temporada",
    "market.popular": "Popular",
    "market.sold": "vendidos",
    "market.sort.relevance": "Relevancia",
    "market.sort.price_asc": "Menor precio",
    "market.sort.price_desc": "Mayor precio",
    "market.sort.proximity": "Más cercano",
    "market.sort.best_seller": "Más vendido",
    "market.sort.cert_green": "Certificado SPG",
    "market.sort.seasonal": "De temporada",
    "market.filter.producer": "Vendedor",
    "market.filter.producer_all": "Todos los vendedores",
    "market.filter.zone": "Zona",
    "market.filter.zone_all": "Todas las zonas",
    "market.filter.type": "Tipo",
    "market.filter.type_all": "Oferta y Demanda",
    "market.filter.oferta": "Oferta (venden)",
    "market.filter.demanda": "Demanda (buscan)",
    "market.clear_filters": "Limpiar filtros",
    "market.badge_oferta": "Oferta",
    "market.badge_demanda": "Demanda",
    // Actors page
    "actors.title": "Miembros de la Red",
    "actors.subtitle": "Directorio de productores, compradores, logística e infraestructura del ecosistema agroecológico.",
    "actors.search": "Buscar actor...",
    "actors.all": "Todos",
    "actors.contact": "Contactar",
    "actors.cap": "Cap",
    // Actor types
    "actor.producer": "Productor/a Agroecológico/a",
    "actor.cooperative": "Cooperativa / Asociación",
    "actor.social_kitchen": "Comedor Comunitario",
    "actor.restaurant": "Restaurante / Bar",
    "actor.retail": "Comercio / Feria",
    "actor.institution": "Institución Pública",
    "actor.logistics": "Proveedor/a Logístico/a",
    "actor.processing": "Planta de Procesamiento",
    // Certification
    "cert.red": "Básico",
    "cert.yellow": "En transición",
    "cert.green": "Certificado",
    "cert.none_spg": "Agroecológico sin SPG",
    // SPG modal
    "spg.peer_visits": "Visitas de pares realizadas",
    "spg.evaluations_done": "Exámenes realizados",
    "spg.methodology": "Metodología",
    "spg.eval_form": "Formulario de evaluación",
    "spg.view_form": "Ver formulario utilizado →",
    "spg.evaluations": "Exámenes realizados",
    "spg.loading": "Cargando...",
    // Eval types
    "eval.suelo": "Suelo",
    "eval.agua": "Agua",
    "eval.biodiversidad": "Biodiversidad",
    "eval.condiciones_laborales": "Condiciones laborales",
    // Categories
    "cat.Verduras": "Verduras",
    "cat.Frutas": "Frutas",
    "cat.Lácteos": "Lácteos",
    "cat.Huevos": "Huevos",
    "cat.Carnes": "Carnes",
    "cat.Almacén": "Almacén",
    "cat.Panificados": "Panificados",
    "cat.Bebidas": "Bebidas",
    "cat.Cosmética Natural": "Cosmética Natural",
    "cat.Plantines y Semillas": "Plantines y Semillas",
    "cat.Salud Natural": "Salud Natural",
    "cat.Mercado Híbrido": "Mercado Híbrido (conv./agroeco.)",
    // Almacén subcategories
    "almacen.all_almacen": "Todo Almacén",
    "almacen.yerba_mate": "Yerba Mate",
    "almacen.cereales": "Cereales y Harinas",
    "almacen.conservas": "Conservas",
    "almacen.miel": "Miel",
    "almacen.mermeladas": "Mermeladas y Dulces",
    "almacen.productos_secos": "Productos Secos",
    "almacen.aceites": "Aceites",
    "almacen.azucar": "Azúcar y Endulzantes",
    // Egg subcategories
    "egg.all_eggs": "Todos los huevos",
    "egg.gallina_pastoril": "Gallina pastoril",
    "egg.pato": "Pato",
    "egg.codorniz": "Codorniz",
    // Disclaimer
    "market.disclaimer_title": "⚠️ Aviso importante sobre vendedores",
    "market.disclaimer_text": "Los usuarios registrados en esta plataforma son autodeclarados. AgroEco.Red no verifica la identidad ni la veracidad de los emprendimientos. Recomendamos tomar precauciones antes de realizar transferencias de dinero: verificá la existencia del emprendimiento, pedí referencias y, de ser posible, coordiná entregas en persona o contra entrega.",
    "market.disclaimer_categories": "Las calificaciones con estrellas y comentarios de otros usuarios pueden ayudarte a evaluar la confiabilidad de un vendedor, pero no reemplazan la verificación personal. Ante cualquier duda, contactá al vendedor antes de comprar.",
    // Reviews
    "market.reviews": "reseñas",
    "market.no_reviews": "Sin reseñas aún",
    "market.write_review": "Escribir reseña",
    "market.review_placeholder": "Contá tu experiencia con este vendedor...",
    "market.review_submit": "Enviar reseña",
    "market.review_login": "Ingresá para dejar una reseña",
    "market.review_thanks": "¡Gracias por tu reseña!",
    // Community nav
    "nav.community": "Comunidad",
    "nav.library": "Biblioteca",
    // Community page
    "community.title": "Comunidad y Co-aprendizaje",
    "community.subtitle": "Espacio de intercambio de conocimiento, experiencias y recursos para la producción agroecológica.",
    "community.forum": "Foro",
    "community.wiki": "Conocimiento",
    "community.events": "Eventos",
    "community.search_forum": "Buscar en el foro...",
    "community.search_wiki": "Buscar artículo...",
    "community.new_post": "Nuevo tema",
    "community.attendees": "inscriptos",
    "community.register_event": "Inscribirme",
    "community.cat.plagas": "Plagas",
    "community.cat.técnicas": "Técnicas",
    "community.cat.suelo": "Suelo",
    "community.cat.semillas": "Semillas",
    "community.cat.certificación": "Certificación",
    "community.event_type.workshop": "Taller",
    "community.event_type.field_day": "Jornada de campo",
    "community.event_type.course": "Curso",
    "community.event_type.meeting": "Encuentro",
    // Cart
    "market.add_cart": "Agregar",
    "cart.title": "Mi Pedido",
    "cart.empty": "Tu carrito está vacío",
    "cart.send_order": "Enviar pedido",
    "cart.order_sent": "¡Pedido enviado!",
    "cart.order_to": "Pedido enviado a",
    "cart.total": "Total estimado",
    "cart.grouped_note": "Los pedidos se agrupan por productor. Cada productor recibirá su pedido por separado.",
    "cart.keep_shopping": "Seguir comprando",
    "cart.send_all": "Enviar todo el pedido",
    "cart.order_whatsapp": "📲 Se abrirá WhatsApp para coordinar la entrega con cada productor.",
    "cart.order_email_sent": "También se enviará un email con el detalle del pedido al productor.",
    "cart.order_next_steps": "Próximos pasos: el productor confirmará disponibilidad, acordarán forma de pago y entrega.",
    // Services
    "nav.services": "Servicios",
    "services.badge": "Soluciones integrales",
    "services.title": "Todo lo que necesitás para tu transición agroecológica",
    "services.subtitle": "Bio-insumos, semillas, asistencia técnica, financiamiento, almacenamiento, logística y más. Tu ventanilla única de confianza.",
    "services.weather_title": "Clima en tu zona",
    "services.humidity": "Humedad",
    "services.wind": "Viento",
    "services.weather_note": "Datos de Open-Meteo. Registrate para ver el pronóstico personalizado según tu ubicación.",
    "services.inputs_title": "Insumos y Semillas",
    "services.inputs_desc": "Accedé a bio-insumos y semillas agroecológicas",
    "services.bio_inputs": "Bio-insumos",
    "services.bio_inputs_desc": "Directorio de proveedores de fertilizantes orgánicos, biopreparados, controladores biológicos y enmiendas.",
    "services.seed_bank": "Banco de Semillas",
    "services.seed_bank_desc": "Intercambio y venta de semillas criollas, nativas y adaptadas localmente. Preservá la biodiversidad.",
    "services.knowledge_title": "Asistencia Técnica",
    "services.knowledge_desc": "Conocimiento y asesoramiento para tu producción",
    "services.library": "Biblioteca Agroecológica",
    "services.library_desc": "Guías, manuales, videos y fichas técnicas sobre manejo agroecológico, control de plagas, fertilidad del suelo y más.",
    "services.advisory": "Asesoría Técnica",
    "services.advisory_desc": "Conectá con técnicos/as y extensionistas especializados/as en producción agroecológica.",
    "services.finance_title": "Financiamiento y Programas",
    "services.finance_desc": "Capital, seguros y programas gubernamentales",
    "services.microcredit": "Microcréditos y Fondos Rotatorios",
    "services.microcredit_desc": "Acceso a financiamiento de bajo costo a través de cooperativas, organizaciones sociales y programas estatales.",
    "services.insurance": "Seguros Agrícolas",
    "services.insurance_desc": "Información sobre seguros multirriesgo y coberturas disponibles para proteger tu producción.",
    "services.gov_programs": "Programas Gubernamentales",
    "services.gov_programs_desc": "Directorio actualizado de programas nacionales y provinciales de apoyo a la agricultura familiar y agroecológica.",
    "services.available_programs": "Programas disponibles",
    "services.prog_prohuerta": "Semillas, capacitación y asistencia técnica para huertas familiares y comunitarias.",
    "services.prog_senasa": "Registro de operadores orgánicos y certificación oficial.",
    "services.prog_saf": "Programas de apoyo, comercialización y fortalecimiento para la agricultura familiar.",
    "services.prog_monotributo": "Régimen tributario simplificado para emprendedores de la economía social.",
    "services.postharvest_title": "Logística y Postcosecha",
    "services.postharvest_desc": "Almacenamiento, procesamiento y distribución",
    "services.storage": "Almacenamiento Compartido",
    "services.storage_desc": "Encontrá centros de acopio y cámaras de frío disponibles cerca tuyo para conservar tu producción.",
    "services.processing": "Valor Agregado",
    "services.processing_desc": "Conectá con plantas de procesamiento, cocinas comunitarias y salas de elaboración para agregar valor a tus productos.",
    "services.logistics": "Logística Colaborativa",
    "services.logistics_desc": "Rutas compartidas, fletes cooperativos y puntos de distribución para reducir costos de transporte.",
    "services.view_on_map": "Ver en el mapa",
    "services.also_explore": "También explorá estas secciones de la plataforma:",
    // Partners
    "partners.badge": "Alianzas institucionales",
    "partners.title": "Nos acompañan",
    "partners.subtitle": "Redes, instituciones y organizaciones que acompañan el desarrollo de la plataforma.",
    "partners.placeholder": "Próximo aliado",
    "partners.cta_title": "¿Tu institución o red quiere sumarse?",
    "partners.cta_text": "Si representás una universidad, organismo de investigación, organización de la sociedad civil o red agroecológica, contactanos para explorar una colaboración.",
    "partners.cta_button": "Escribinos",
  },
  en: {
    "nav.home": "Home",
    "nav.map": "Map",
    "nav.market": "Market",
    "nav.actors": "Network",
    "nav.register": "Sign Up",
    "nav.login": "Log In",
    "nav.logout": "Log Out",
    "hero.badge": "Traceability · Participatory Certification · Short Chains",
    "hero.title_1": "The network that connects the ",
    "hero.title_highlight": "agroecological farms",
    "hero.subtitle": "Interactive map, marketplace and traceability for producers, cooperatives, community kitchens, restaurants and consumers.",
    "hero.cta_map": "Explore the Map",
    "hero.cta_market": "View Market",
    "hero.stat_producers": "Producers",
    "hero.stat_points": "Points of sale",
    "hero.stat_kitchens": "Kitchens",
    "hero.stat_regions": "Regions",
    "features.badge": "Platform modules",
    "features.title": "Digital infrastructure for agroecological supply chains",
    "features.subtitle": "Each module is designed to connect actors, reduce intermediaries and strengthen food sovereignty.",
    "features.map": "Agroecological Map",
    "features.map_desc": "View geolocated producers, cooperatives, kitchens and points of sale with filters by product and certification.",
    "features.marketplace": "Marketplace",
    "features.marketplace_desc": "Supply and demand for agroecological food with automatic proximity-based matching.",
    "features.cert": "Participatory Certification (SPG)",
    "features.cert_desc": "Access how each SPG works, evaluation questionnaires, peer visits, certification levels and community validation. Full transparency.",
    "features.logistics": "Smart Logistics",
    "features.logistics_desc": "Route optimization, available trucks, collection centers and shared distribution capacity to reduce costs and ecological footprint.",
    "features.comm": "Communication Network",
    "features.comm_desc": "Direct messaging, regional groups and real-time supply and demand notifications.",
    "features.dashboard": "Analytics Dashboard",
    "features.dashboard_desc": "Impact metrics, production planning, demand forecasting and environmental indicators.",
    "features.scalable": "Modular & Scalable",
    "features.scalable_desc": "New regions and institutions can easily join the platform ecosystem.",
    "features.services": "Holistic Services",
    "features.services_desc": "Bio-inputs, seeds, technical assistance, financing, storage and logistics. Everything for your agroecological transition.",
    "actors_section.badge": "Multi-actor ecosystem",
    "actors_section.title": "All links in the chain, connected",
    "actors_section.subtitle": "From farm to table, every actor in the food system has a place in the network.",
    "actors_section.producers": "Agroecological Producers",
    "actors_section.cooperatives": "Cooperatives & Associations",
    "actors_section.kitchens": "Community Kitchens",
    "actors_section.schools": "Schools & Universities",
    "actors_section.consumers": "Individual Consumers",
    "actors_section.restaurants": "Restaurants & Bars",
    "actors_section.retail": "Shops & Fairs",
    "actors_section.institutions": "Public Institutions",
    "actors_section.logistics": "Logistics Providers",
    "actors_section.processing": "Processing Plants",
    "cta.badge": "Over 1,200 actors are already part of it",
    "cta.title": "Join the agroecological network",
    "cta.subtitle": "Offer your products, find what you need nearby, and be part of a fairer, more sustainable food economy.",
    "cta.register": "Register now",
    "cta.explore": "Explore the map",
    "footer.description": "Digital platform for mapping, connecting and marketing agroecological food. Short chains, sustainable production, fair trade.",
    "footer.platform": "Platform",
    "footer.interactive_map": "Interactive Map",
    "footer.marketplace": "Marketplace",
    "footer.actor_network": "Network Members",
    "footer.register": "Sign Up",
    "footer.resources": "Resources",
    "footer.api_docs": "API Documentation",
    "footer.participatory_cert": "Participatory Certification",
    "footer.contact": "Contact",
    "footer.copyright": "© 2026 AgroEco.Red. Food sovereignty and agroecology.",
    "footer.tagline": "Made with 🌱 for the earth",
    "market.title": "Agroecological Market",
    "market.subtitle": "Fresh products directly from certified agroecological producers. No intermediaries, with full traceability.",
    "market.search": "Search product or producer...",
    "market.all": "All",
    "market.products_available": "products available",
    "market.clear_sort": "Clear sort",
    "market.contact": "Contact",
    "market.in_season": "In season",
    "market.popular": "Popular",
    "market.sold": "sold",
    "market.sort.relevance": "Relevance",
    "market.sort.price_asc": "Lowest price",
    "market.sort.price_desc": "Highest price",
    "market.sort.proximity": "Nearest",
    "market.sort.best_seller": "Best seller",
    "market.sort.cert_green": "SPG Certified",
    "market.sort.seasonal": "In season",
    "market.filter.producer": "Seller",
    "market.filter.producer_all": "All sellers",
    "market.filter.zone": "Zone",
    "market.filter.zone_all": "All zones",
    "market.filter.type": "Type",
    "market.filter.type_all": "Supply & Demand",
    "market.filter.oferta": "Supply (selling)",
    "market.filter.demanda": "Demand (buying)",
    "market.clear_filters": "Clear filters",
    "market.badge_oferta": "Supply",
    "market.badge_demanda": "Demand",
    "actors.title": "Network Members",
    "actors.subtitle": "Directory of producers, buyers, logistics and infrastructure of the agroecological ecosystem.",
    "actors.search": "Search actor...",
    "actors.all": "All",
    "actors.contact": "Contact",
    "actors.cap": "Cap",
    "actor.producer": "Producer",
    "actor.cooperative": "Cooperative",
    "actor.social_kitchen": "Kitchen",
    "actor.restaurant": "Restaurant",
    "actor.retail": "Retail",
    "actor.institution": "Institution",
    "actor.logistics": "Logistics",
    "actor.processing": "Processing",
    "cert.red": "Basic",
    "cert.yellow": "In transition",
    "cert.green": "Certified",
    "cert.none_spg": "Agroecological (no SPG)",
    "spg.peer_visits": "Peer visits completed",
    "spg.evaluations_done": "Evaluations completed",
    "spg.methodology": "Methodology",
    "spg.eval_form": "Evaluation form",
    "spg.view_form": "View form used →",
    "spg.evaluations": "Evaluations completed",
    "spg.loading": "Loading...",
    "eval.suelo": "Soil",
    "eval.agua": "Water",
    "eval.biodiversidad": "Biodiversity",
    "eval.condiciones_laborales": "Working conditions",
    "cat.Verduras": "Vegetables",
    "cat.Frutas": "Fruits",
    "cat.Lácteos": "Dairy",
    "cat.Huevos": "Eggs",
    "cat.Carnes": "Meats",
    "cat.Almacén": "Pantry",
    "cat.Panificados": "Bakery",
    "cat.Bebidas": "Beverages",
    "cat.Cosmética Natural": "Natural Cosmetics",
    "cat.Plantines y Semillas": "Seedlings & Seeds",
    "cat.Salud Natural": "Natural Health",
    "cat.Mercado Híbrido": "Hybrid Market (conv./agroeco.)",
    "almacen.all_almacen": "All Pantry",
    "almacen.yerba_mate": "Yerba Mate",
    "almacen.cereales": "Grains & Flour",
    "almacen.conservas": "Preserves",
    "almacen.miel": "Honey",
    "almacen.mermeladas": "Jams & Spreads",
    "almacen.productos_secos": "Dried Goods",
    "almacen.aceites": "Oils",
    "almacen.azucar": "Sugar & Sweeteners",
    "egg.all_eggs": "All eggs",
    "egg.gallina_pastoril": "Free-range hen",
    "egg.pato": "Duck",
    "egg.codorniz": "Quail",
    "market.disclaimer_title": "⚠️ Important notice about sellers",
    "market.disclaimer_text": "Users registered on this platform are self-declared. AgroEco.Red does not verify the identity or legitimacy of businesses. We recommend taking precautions before transferring money: verify the business exists, ask for references, and if possible, coordinate in-person or cash-on-delivery transactions.",
    "market.disclaimer_categories": "Star ratings and comments from other users can help you evaluate a seller's reliability, but they do not replace personal verification. If in doubt, contact the seller before purchasing.",
    "market.reviews": "reviews",
    "market.no_reviews": "No reviews yet",
    "market.write_review": "Write review",
    "market.review_placeholder": "Share your experience with this seller...",
    "market.review_submit": "Submit review",
    "market.review_login": "Log in to leave a review",
    "market.review_thanks": "Thanks for your review!",
    "nav.library": "Library",
    "nav.community": "Community",
    "community.title": "Community & Co-learning",
    "community.subtitle": "Space for sharing knowledge, experiences and resources for agroecological production.",
    "community.forum": "Forum",
    "community.wiki": "Knowledge",
    "community.events": "Events",
    "community.search_forum": "Search forum...",
    "community.search_wiki": "Search article...",
    "community.new_post": "New topic",
    "community.attendees": "registered",
    "community.register_event": "Register",
    "community.cat.plagas": "Pests",
    "community.cat.técnicas": "Techniques",
    "community.cat.suelo": "Soil",
    "community.cat.semillas": "Seeds",
    "community.cat.certificación": "Certification",
    "community.event_type.workshop": "Workshop",
    "community.event_type.field_day": "Field day",
    "community.event_type.course": "Course",
    "community.event_type.meeting": "Meeting",
    "market.add_cart": "Add",
    "cart.title": "My Order",
    "cart.empty": "Your cart is empty",
    "cart.send_order": "Send order",
    "cart.order_sent": "Order sent!",
    "cart.order_to": "Order sent to",
    "cart.total": "Estimated total",
    "cart.grouped_note": "Orders are grouped by producer. Each producer will receive their order separately.",
    "cart.keep_shopping": "Keep shopping",
    "cart.send_all": "Send entire order",
    "cart.order_whatsapp": "📲 WhatsApp will open to coordinate delivery with each producer.",
    "cart.order_email_sent": "An email with the order details will also be sent to the producer.",
    "cart.order_next_steps": "Next steps: the producer will confirm availability, and you'll agree on payment and delivery.",
    "nav.services": "Services",
    "services.badge": "Holistic solutions",
    "services.title": "Everything you need for your agroecological transition",
    "services.subtitle": "Bio-inputs, seeds, technical assistance, financing, storage, logistics and more. Your trusted one-stop shop.",
    "services.weather_title": "Weather in your area",
    "services.humidity": "Humidity",
    "services.wind": "Wind",
    "services.weather_note": "Data from Open-Meteo. Register to see personalized forecasts based on your location.",
    "services.inputs_title": "Inputs & Seeds",
    "services.inputs_desc": "Access bio-inputs and agroecological seeds",
    "services.bio_inputs": "Bio-inputs",
    "services.bio_inputs_desc": "Directory of suppliers of organic fertilizers, biopreparations, biological controllers and amendments.",
    "services.seed_bank": "Seed Bank",
    "services.seed_bank_desc": "Exchange and sale of native and locally adapted seeds. Preserve biodiversity.",
    "services.knowledge_title": "Technical Assistance",
    "services.knowledge_desc": "Knowledge and advisory for your production",
    "services.library": "Agroecological Library",
    "services.library_desc": "Guides, manuals, videos and technical sheets on agroecological management, pest control, soil fertility and more.",
    "services.advisory": "Technical Advisory",
    "services.advisory_desc": "Connect with technicians and extensionists specialized in agroecological production.",
    "services.finance_title": "Financing & Programs",
    "services.finance_desc": "Capital, insurance and government programs",
    "services.microcredit": "Microcredit & Revolving Funds",
    "services.microcredit_desc": "Access to low-cost financing through cooperatives, social organizations and state programs.",
    "services.insurance": "Agricultural Insurance",
    "services.insurance_desc": "Information on multi-risk insurance and available coverages to protect your production.",
    "services.gov_programs": "Government Programs",
    "services.gov_programs_desc": "Updated directory of national and provincial support programs for family and agroecological farming.",
    "services.available_programs": "Available programs",
    "services.prog_prohuerta": "Seeds, training and technical assistance for family and community gardens.",
    "services.prog_senasa": "Organic operator registry and official certification.",
    "services.prog_saf": "Support, marketing and strengthening programs for family farming.",
    "services.prog_monotributo": "Simplified tax regime for social economy entrepreneurs.",
    "services.postharvest_title": "Logistics & Post-harvest",
    "services.postharvest_desc": "Storage, processing and distribution",
    "services.storage": "Shared Storage",
    "services.storage_desc": "Find collection centers and cold rooms available near you to preserve your production.",
    "services.processing": "Value Addition",
    "services.processing_desc": "Connect with processing plants, community kitchens and production rooms to add value to your products.",
    "services.logistics": "Collaborative Logistics",
    "services.logistics_desc": "Shared routes, cooperative freight and distribution points to reduce transport costs.",
    "services.view_on_map": "View on map",
    "services.also_explore": "Also explore these platform sections:",
    // Partners
    "partners.badge": "Institutional alliances",
    "partners.title": "They support us",
    "partners.subtitle": "Networks, institutions and organizations that support the development of the platform.",
    "partners.placeholder": "Next ally",
    "partners.cta_title": "Does your institution or network want to join?",
    "partners.cta_text": "If you represent a university, research body, civil society organization or agroecological network, contact us to explore a collaboration.",
    "partners.cta_button": "Contact us",
  },
  fr: {
    "nav.home": "Accueil",
    "nav.map": "Carte",
    "nav.market": "Marché",
    "nav.actors": "Réseau",
    "nav.register": "S'inscrire",
    "nav.login": "Connexion",
    "nav.logout": "Déconnexion",
    "hero.badge": "Traçabilité · Certification Participative · Circuits Courts",
    "hero.title_1": "Le réseau qui relie l'agriculture agroécologique à ",
    "hero.title_highlight": "votre table",
    "hero.subtitle": "Carte interactive, marketplace et traçabilité pour producteurs, coopératives, cantines, restaurants et consommateurs.",
    "hero.cta_map": "Explorer la carte",
    "hero.cta_market": "Voir le marché",
    "hero.stat_producers": "Producteurs",
    "hero.stat_points": "Points de vente",
    "hero.stat_kitchens": "Cantines",
    "hero.stat_regions": "Régions",
    "features.badge": "Modules de la plateforme",
    "features.title": "Infrastructure numérique pour les chaînes agroécologiques",
    "features.subtitle": "Chaque module est conçu pour connecter les acteurs, réduire les intermédiaires et renforcer la souveraineté alimentaire.",
    "features.map": "Carte Agroécologique",
    "features.map_desc": "Visualisez les producteurs, coopératives, cantines et points de vente géolocalisés avec filtres par produit et certification.",
    "features.marketplace": "Marketplace",
    "features.marketplace_desc": "Offre et demande d'aliments agroécologiques avec mise en relation automatique par proximité.",
    "features.cert": "Certification Participative (SPG)",
    "features.cert_desc": "Accédez au fonctionnement de chaque SPG, questionnaires d'évaluation, visites de pairs, niveaux de certification et validation communautaire.",
    "features.logistics": "Logistique Intelligente",
    "features.logistics_desc": "Optimisation des routes, camions disponibles, centres de collecte et capacité de distribution partagée pour réduire les coûts et l'empreinte écologique.",
    "features.comm": "Réseau de Communication",
    "features.comm_desc": "Messagerie directe, groupes régionaux et notifications d'offre et demande en temps réel.",
    "features.dashboard": "Tableau de Bord Analytique",
    "features.dashboard_desc": "Métriques d'impact, planification de production, prévision de demande et indicateurs environnementaux.",
    "features.scalable": "Modulaire et Évolutif",
    "features.scalable_desc": "De nouvelles régions et institutions peuvent facilement rejoindre l'écosystème de la plateforme.",
    "features.services": "Services Intégraux",
    "features.services_desc": "Bio-intrants, semences, assistance technique, financement, stockage et logistique pour votre transition.",
    "actors_section.badge": "Écosystème multi-acteurs",
    "actors_section.title": "Tous les maillons de la chaîne, connectés",
    "actors_section.subtitle": "Du champ à la table, chaque acteur du système alimentaire a sa place dans le réseau.",
    "actors_section.producers": "Producteurs Agroécologiques",
    "actors_section.cooperatives": "Coopératives et Associations",
    "actors_section.kitchens": "Cantines Communautaires",
    "actors_section.schools": "Écoles et Universités",
    "actors_section.consumers": "Consommateurs Individuels",
    "actors_section.restaurants": "Restaurants et Bars",
    "actors_section.retail": "Commerces et Foires",
    "actors_section.institutions": "Institutions Publiques",
    "actors_section.logistics": "Prestataires Logistiques",
    "actors_section.processing": "Usines de Transformation",
    "cta.badge": "Plus de 1 200 acteurs en font déjà partie",
    "cta.title": "Rejoignez le réseau agroécologique",
    "cta.subtitle": "Proposez vos produits, trouvez ce dont vous avez besoin et participez à une économie alimentaire plus juste et durable.",
    "cta.register": "S'inscrire maintenant",
    "cta.explore": "Explorer la carte",
    "footer.description": "Plateforme numérique pour la cartographie, la connexion et la commercialisation d'aliments agroécologiques. Circuits courts, production durable, commerce équitable.",
    "footer.platform": "Plateforme",
    "footer.interactive_map": "Carte Interactive",
    "footer.marketplace": "Marketplace",
    "footer.actor_network": "Membres du Réseau",
    "footer.register": "S'inscrire",
    "footer.resources": "Ressources",
    "footer.api_docs": "Documentation API",
    "footer.participatory_cert": "Certification Participative",
    "footer.contact": "Contact",
    "footer.copyright": "© 2026 AgroEco.Red. Souveraineté alimentaire et agroécologie.",
    "footer.tagline": "Fait avec 🌱 pour la terre",
    "market.title": "Marché Agroécologique",
    "market.subtitle": "Produits frais directement des producteurs agroécologiques certifiés. Sans intermédiaires, avec traçabilité complète.",
    "market.search": "Chercher produit ou producteur...",
    "market.all": "Tous",
    "market.products_available": "produits disponibles",
    "market.clear_sort": "Effacer le tri",
    "market.contact": "Contacter",
    "market.in_season": "De saison",
    "market.popular": "Populaire",
    "market.sold": "vendus",
    "market.sort.relevance": "Pertinence",
    "market.sort.price_asc": "Prix croissant",
    "market.sort.price_desc": "Prix décroissant",
    "market.sort.proximity": "Plus proche",
    "market.sort.best_seller": "Plus vendu",
    "market.sort.cert_green": "Certifié SPG",
    "market.sort.seasonal": "De saison",
    "market.filter.producer": "Vendeur",
    "market.filter.producer_all": "Tous les vendeurs",
    "market.filter.zone": "Zone",
    "market.filter.zone_all": "Toutes les zones",
    "market.filter.type": "Type",
    "market.filter.type_all": "Offre et Demande",
    "market.filter.oferta": "Offre (vendent)",
    "market.filter.demanda": "Demande (cherchent)",
    "market.clear_filters": "Effacer les filtres",
    "market.badge_oferta": "Offre",
    "market.badge_demanda": "Demande",
    "actors.title": "Membres du Réseau",
    "actors.subtitle": "Répertoire des producteurs, acheteurs, logistique et infrastructure de l'écosystème agroécologique.",
    "actors.search": "Chercher acteur...",
    "actors.all": "Tous",
    "actors.contact": "Contacter",
    "actors.cap": "Cap",
    "actor.producer": "Producteur",
    "actor.cooperative": "Coopérative",
    "actor.social_kitchen": "Cantine",
    "actor.restaurant": "Restaurant",
    "actor.retail": "Commerce",
    "actor.institution": "Institution",
    "actor.logistics": "Logistique",
    "actor.processing": "Transformation",
    "cert.red": "Basique",
    "cert.yellow": "En transition",
    "cert.green": "Certifié",
    "cert.none_spg": "Agroécologique (sans SPG)",
    "spg.peer_visits": "Visites de pairs réalisées",
    "spg.evaluations_done": "Évaluations réalisées",
    "spg.methodology": "Méthodologie",
    "spg.eval_form": "Formulaire d'évaluation",
    "spg.view_form": "Voir le formulaire utilisé →",
    "spg.evaluations": "Évaluations réalisées",
    "spg.loading": "Chargement...",
    "eval.suelo": "Sol",
    "eval.agua": "Eau",
    "eval.biodiversidad": "Biodiversité",
    "eval.condiciones_laborales": "Conditions de travail",
    "cat.Verduras": "Légumes",
    "cat.Frutas": "Fruits",
    "cat.Lácteos": "Produits laitiers",
    "cat.Huevos": "Œufs",
    "cat.Carnes": "Viandes",
    "cat.Almacén": "Épicerie",
    "cat.Panificados": "Boulangerie",
    "cat.Bebidas": "Boissons",
    "cat.Cosmética Natural": "Cosmétique Naturelle",
    "cat.Plantines y Semillas": "Plants et Graines",
    "cat.Salud Natural": "Santé Naturelle",
    "cat.Mercado Híbrido": "Marché Hybride (conv./agroéco.)",
    "almacen.all_almacen": "Toute l'Épicerie",
    "almacen.yerba_mate": "Yerba Maté",
    "almacen.cereales": "Céréales et Farines",
    "almacen.conservas": "Conserves",
    "almacen.miel": "Miel",
    "almacen.mermeladas": "Confitures",
    "almacen.productos_secos": "Produits Secs",
    "almacen.aceites": "Huiles",
    "almacen.azucar": "Sucre et Édulcorants",
    "egg.all_eggs": "Tous les œufs",
    "egg.gallina_pastoril": "Poule plein air",
    "egg.pato": "Canard",
    "egg.codorniz": "Caille",
    "market.disclaimer_title": "⚠️ Avis important sur les vendeurs",
    "market.disclaimer_text": "Les utilisateurs inscrits sur cette plateforme sont auto-déclarés. AgroEco.Red ne vérifie pas l'identité ni la véracité des entreprises. Nous recommandons de prendre des précautions avant de transférer de l'argent : vérifiez l'existence de l'entreprise, demandez des références et, si possible, coordonnez des livraisons en personne ou contre remboursement.",
    "market.disclaimer_categories": "Les évaluations par étoiles et les commentaires d'autres utilisateurs peuvent vous aider à évaluer la fiabilité d'un vendeur, mais ne remplacent pas la vérification personnelle. En cas de doute, contactez le vendeur avant d'acheter.",
    "market.reviews": "avis",
    "market.no_reviews": "Pas encore d'avis",
    "market.write_review": "Écrire un avis",
    "market.review_placeholder": "Partagez votre expérience avec ce vendeur...",
    "market.review_submit": "Envoyer l'avis",
    "market.review_login": "Connectez-vous pour laisser un avis",
    "nav.library": "Bibliothèque",
    "market.review_thanks": "Merci pour votre avis !",
    "nav.community": "Communauté",
    "community.title": "Communauté et Co-apprentissage",
    "community.subtitle": "Espace d'échange de connaissances, d'expériences et de ressources pour la production agroécologique.",
    "community.forum": "Forum",
    "community.wiki": "Connaissances",
    "community.events": "Événements",
    "community.search_forum": "Chercher dans le forum...",
    "community.search_wiki": "Chercher un article...",
    "community.new_post": "Nouveau sujet",
    "community.attendees": "inscrits",
    "community.register_event": "S'inscrire",
    "community.cat.plagas": "Parasites",
    "community.cat.técnicas": "Techniques",
    "community.cat.suelo": "Sol",
    "community.cat.semillas": "Semences",
    "community.cat.certificación": "Certification",
    "community.event_type.workshop": "Atelier",
    "community.event_type.field_day": "Journée de terrain",
    "community.event_type.course": "Formation",
    "community.event_type.meeting": "Rencontre",
    "market.add_cart": "Ajouter",
    "cart.title": "Ma Commande",
    "cart.empty": "Votre panier est vide",
    "cart.send_order": "Envoyer la commande",
    "cart.order_sent": "Commande envoyée !",
    "cart.order_to": "Commande envoyée à",
    "cart.total": "Total estimé",
    "cart.grouped_note": "Les commandes sont regroupées par producteur. Chaque producteur recevra sa commande séparément.",
    "cart.keep_shopping": "Continuer les achats",
    "cart.send_all": "Envoyer toute la commande",
    "cart.order_whatsapp": "📲 WhatsApp s'ouvrira pour coordonner la livraison avec chaque producteur.",
    "cart.order_email_sent": "Un email avec les détails de la commande sera également envoyé au producteur.",
    "cart.order_next_steps": "Prochaines étapes : le producteur confirmera la disponibilité, et vous conviendrez du paiement et de la livraison.",
    "nav.services": "Services",
    "services.badge": "Solutions intégrales",
    "services.title": "Tout ce dont vous avez besoin pour votre transition agroécologique",
    "services.subtitle": "Bio-intrants, semences, assistance technique, financement, stockage, logistique et plus encore.",
    "services.weather_title": "Météo dans votre zone",
    "services.humidity": "Humidité",
    "services.wind": "Vent",
    "services.weather_note": "Données Open-Meteo. Inscrivez-vous pour des prévisions personnalisées.",
    "services.inputs_title": "Intrants et Semences",
    "services.inputs_desc": "Accédez aux bio-intrants et semences agroécologiques",
    "services.bio_inputs": "Bio-intrants",
    "services.bio_inputs_desc": "Répertoire de fournisseurs d'engrais organiques, biopréparations et amendements.",
    "services.seed_bank": "Banque de Semences",
    "services.seed_bank_desc": "Échange et vente de semences natives et adaptées localement.",
    "services.knowledge_title": "Assistance Technique",
    "services.knowledge_desc": "Connaissances et conseils pour votre production",
    "services.library": "Bibliothèque Agroécologique",
    "services.library_desc": "Guides, manuels, vidéos et fiches techniques sur la gestion agroécologique.",
    "services.advisory": "Conseil Technique",
    "services.advisory_desc": "Connectez-vous avec des techniciens spécialisés en production agroécologique.",
    "services.finance_title": "Financement et Programmes",
    "services.finance_desc": "Capital, assurances et programmes gouvernementaux",
    "services.microcredit": "Microcrédits",
    "services.microcredit_desc": "Accès au financement à faible coût via coopératives et programmes d'État.",
    "services.insurance": "Assurance Agricole",
    "services.insurance_desc": "Informations sur les assurances multirisques disponibles.",
    "services.gov_programs": "Programmes Gouvernementaux",
    "services.gov_programs_desc": "Répertoire des programmes de soutien à l'agriculture familiale.",
    "services.available_programs": "Programmes disponibles",
    "services.prog_prohuerta": "Semences, formation et assistance technique.",
    "services.prog_senasa": "Registre des opérateurs biologiques.",
    "services.prog_saf": "Programmes de soutien à l'agriculture familiale.",
    "services.prog_monotributo": "Régime fiscal simplifié pour l'économie sociale.",
    "services.postharvest_title": "Logistique et Post-récolte",
    "services.postharvest_desc": "Stockage, transformation et distribution",
    "services.storage": "Stockage Partagé",
    "services.storage_desc": "Trouvez des centres de collecte et chambres froides près de chez vous.",
    "services.processing": "Valeur Ajoutée",
    "services.processing_desc": "Connectez-vous avec des usines de transformation et cuisines communautaires.",
    "services.logistics": "Logistique Collaborative",
    "services.logistics_desc": "Routes partagées et points de distribution pour réduire les coûts.",
    "services.view_on_map": "Voir sur la carte",
    "services.also_explore": "Explorez aussi ces sections :",
    // Partners
    "partners.badge": "Alliances institutionnelles",
    "partners.title": "Ils nous accompagnent",
    "partners.subtitle": "Réseaux, institutions et organisations qui accompagnent le développement de la plateforme.",
    "partners.placeholder": "Prochain allié",
    "partners.cta_title": "Votre institution ou réseau souhaite se joindre ?",
    "partners.cta_text": "Si vous représentez une université, un organisme de recherche, une organisation de la société civile ou un réseau agroécologique, contactez-nous pour explorer une collaboration.",
    "partners.cta_button": "Contactez-nous",
  },
  pt: {
    "nav.home": "Início",
    "nav.map": "Mapa",
    "nav.market": "Mercado",
    "nav.actors": "Rede",
    "nav.register": "Cadastrar",
    "nav.login": "Entrar",
    "nav.logout": "Sair",
    "hero.badge": "Rastreabilidade · Certificação Participativa · Cadeias Curtas",
    "hero.title_1": "A rede que conecta o campo agroecológico à ",
    "hero.title_highlight": "sua mesa",
    "hero.subtitle": "Mapa interativo, marketplace e rastreabilidade para produtores, cooperativas, refeitórios, restaurantes e consumidores.",
    "hero.cta_map": "Explorar o Mapa",
    "hero.cta_market": "Ver Mercado",
    "hero.stat_producers": "Produtores",
    "hero.stat_points": "Pontos de venda",
    "hero.stat_kitchens": "Refeitórios",
    "hero.stat_regions": "Regiões",
    "features.badge": "Módulos da plataforma",
    "features.title": "Infraestrutura digital para cadeias agroecológicas",
    "features.subtitle": "Cada módulo é projetado para conectar atores, reduzir intermediários e fortalecer a soberania alimentar.",
    "features.map": "Mapa Agroecológico",
    "features.map_desc": "Visualize produtores, cooperativas, refeitórios e pontos de venda geolocalizados com filtros por produto e certificação.",
    "features.marketplace": "Marketplace",
    "features.marketplace_desc": "Oferta e demanda de alimentos agroecológicos com correspondência automática por proximidade geográfica.",
    "features.cert": "Certificação Participativa (SPG)",
    "features.cert_desc": "Acesse como funciona cada SPG, questionários de avaliação, visitas de pares, níveis de certificação e validação comunitária. Transparência total.",
    "features.logistics": "Logística Inteligente",
    "features.logistics_desc": "Otimização de rotas, caminhões disponíveis, centros de coleta e capacidade de distribuição compartilhada para reduzir custos e pegada ecológica.",
    "features.comm": "Rede de Comunicação",
    "features.comm_desc": "Mensagens diretas, grupos regionais e notificações de oferta e demanda em tempo real.",
    "features.dashboard": "Painel Analítico",
    "features.dashboard_desc": "Métricas de impacto, planejamento de produção, previsão de demanda e indicadores ambientais.",
    "features.scalable": "Modular e Escalável",
    "features.scalable_desc": "Novas regiões e instituições podem se integrar facilmente ao ecossistema da plataforma.",
    "features.services": "Serviços Integrais",
    "features.services_desc": "Bio-insumos, sementes, assistência técnica, financiamento, armazenamento e logística para sua transição.",
    "actors_section.badge": "Ecossistema multi-ator",
    "actors_section.title": "Todos os elos da cadeia, conectados",
    "actors_section.subtitle": "Do campo à mesa, cada ator do sistema alimentar tem seu lugar na rede.",
    "actors_section.producers": "Produtores Agroecológicos",
    "actors_section.cooperatives": "Cooperativas e Associações",
    "actors_section.kitchens": "Refeitórios Comunitários",
    "actors_section.schools": "Escolas e Universidades",
    "actors_section.consumers": "Consumidores Individuais",
    "actors_section.restaurants": "Restaurantes e Bares",
    "actors_section.retail": "Comércios e Feiras",
    "actors_section.institutions": "Instituições Públicas",
    "actors_section.logistics": "Provedores de Logística",
    "actors_section.processing": "Plantas de Processamento",
    "cta.badge": "Mais de 1.200 atores já fazem parte",
    "cta.title": "Junte-se à rede agroecológica",
    "cta.subtitle": "Ofereça seus produtos, encontre o que precisa perto de você e faça parte de uma economia alimentar mais justa e sustentável.",
    "cta.register": "Cadastrar agora",
    "cta.explore": "Explorar o mapa",
    "footer.description": "Plataforma digital para mapeamento, conexão e comercialização de alimentos agroecológicos. Cadeias curtas, produção sustentável, comércio justo.",
    "footer.platform": "Plataforma",
    "footer.interactive_map": "Mapa Interativo",
    "footer.marketplace": "Marketplace",
    "footer.actor_network": "Membros da Rede",
    "footer.register": "Cadastrar",
    "footer.resources": "Recursos",
    "footer.api_docs": "Documentação API",
    "footer.participatory_cert": "Certificação Participativa",
    "footer.contact": "Contato",
    "footer.copyright": "© 2026 AgroEco.Red. Soberania alimentar e agroecologia.",
    "footer.tagline": "Feito com 🌱 para a terra",
    "market.title": "Mercado Agroecológico",
    "market.subtitle": "Produtos frescos diretamente de produtores agroecológicos certificados. Sem intermediários, com rastreabilidade completa.",
    "market.search": "Buscar produto ou produtor...",
    "market.all": "Todos",
    "market.products_available": "produtos disponíveis",
    "market.clear_sort": "Limpar ordem",
    "market.contact": "Contatar",
    "market.in_season": "Da temporada",
    "market.popular": "Popular",
    "market.sold": "vendidos",
    "market.sort.relevance": "Relevância",
    "market.sort.price_asc": "Menor preço",
    "market.sort.price_desc": "Maior preço",
    "market.sort.proximity": "Mais perto",
    "market.sort.best_seller": "Mais vendido",
    "market.sort.cert_green": "Certificado SPG",
    "market.sort.seasonal": "Da temporada",
    "market.filter.producer": "Vendedor",
    "market.filter.producer_all": "Todos os vendedores",
    "market.filter.zone": "Zona",
    "market.filter.zone_all": "Todas as zonas",
    "market.filter.type": "Tipo",
    "market.filter.type_all": "Oferta e Demanda",
    "market.filter.oferta": "Oferta (vendem)",
    "market.filter.demanda": "Demanda (buscam)",
    "market.clear_filters": "Limpar filtros",
    "market.badge_oferta": "Oferta",
    "market.badge_demanda": "Demanda",
    "actors.title": "Membros da Rede",
    "actors.subtitle": "Diretório de produtores, compradores, logística e infraestrutura do ecossistema agroecológico.",
    "actors.search": "Buscar ator...",
    "actors.all": "Todos",
    "actors.contact": "Contatar",
    "actors.cap": "Cap",
    "actor.producer": "Produtor",
    "actor.cooperative": "Cooperativa",
    "actor.social_kitchen": "Refeitório",
    "actor.restaurant": "Restaurante",
    "actor.retail": "Comércio",
    "actor.institution": "Instituição",
    "actor.logistics": "Logística",
    "actor.processing": "Processamento",
    "cert.red": "Básico",
    "cert.yellow": "Em transição",
    "cert.green": "Certificado",
    "cert.none_spg": "Agroecológico (sem SPG)",
    "spg.peer_visits": "Visitas de pares realizadas",
    "spg.evaluations_done": "Avaliações realizadas",
    "spg.methodology": "Metodologia",
    "spg.eval_form": "Formulário de avaliação",
    "spg.view_form": "Ver formulário utilizado →",
    "spg.evaluations": "Avaliações realizadas",
    "spg.loading": "Carregando...",
    "eval.suelo": "Solo",
    "eval.agua": "Água",
    "eval.biodiversidad": "Biodiversidade",
    "eval.condiciones_laborales": "Condições de trabalho",
    "cat.Verduras": "Verduras",
    "cat.Frutas": "Frutas",
    "cat.Lácteos": "Laticínios",
    "cat.Huevos": "Ovos",
    "cat.Carnes": "Carnes",
    "cat.Almacén": "Mercearia",
    "cat.Panificados": "Padaria",
    "cat.Bebidas": "Bebidas",
    "cat.Cosmética Natural": "Cosmética Natural",
    "cat.Plantines y Semillas": "Mudas e Sementes",
    "cat.Salud Natural": "Saúde Natural",
    "cat.Mercado Híbrido": "Mercado Híbrido (conv./agroeco.)",
    "almacen.all_almacen": "Toda Mercearia",
    "almacen.yerba_mate": "Erva-Mate",
    "almacen.cereales": "Cereais e Farinhas",
    "almacen.conservas": "Conservas",
    "almacen.miel": "Mel",
    "almacen.mermeladas": "Geleias e Doces",
    "almacen.productos_secos": "Produtos Secos",
    "almacen.aceites": "Óleos",
    "almacen.azucar": "Açúcar e Adoçantes",
    "egg.all_eggs": "Todos os ovos",
    "egg.gallina_pastoril": "Galinha caipira",
    "egg.pato": "Pato",
    "egg.codorniz": "Codorna",
    "market.disclaimer_title": "⚠️ Aviso importante sobre vendedores",
    "market.disclaimer_text": "Os usuários cadastrados nesta plataforma são autodeclarados. AgroEco.Red não verifica a identidade nem a veracidade dos empreendimentos. Recomendamos tomar precauções antes de transferir dinheiro: verifique a existência do empreendimento, peça referências e, se possível, coordene entregas presenciais ou contra entrega.",
    "market.disclaimer_categories": "As avaliações com estrelas e comentários de outros usuários podem ajudá-lo a avaliar a confiabilidade de um vendedor, mas não substituem a verificação pessoal. Em caso de dúvida, entre em contato com o vendedor antes de comprar.",
    "market.reviews": "avaliações",
    "market.no_reviews": "Sem avaliações ainda",
    "market.write_review": "Escrever avaliação",
    "market.review_placeholder": "Conte sua experiência com este vendedor...",
    "market.review_submit": "Enviar avaliação",
    "nav.library": "Biblioteca",
    "market.review_login": "Faça login para deixar uma avaliação",
    "market.review_thanks": "Obrigado pela sua avaliação!",
    "nav.community": "Comunidade",
    "community.title": "Comunidade e Co-aprendizagem",
    "community.subtitle": "Espaço de troca de conhecimento, experiências e recursos para a produção agroecológica.",
    "community.forum": "Fórum",
    "community.wiki": "Conhecimento",
    "community.events": "Eventos",
    "community.search_forum": "Buscar no fórum...",
    "community.search_wiki": "Buscar artigo...",
    "community.new_post": "Novo tópico",
    "community.attendees": "inscritos",
    "community.register_event": "Inscrever-se",
    "community.cat.plagas": "Pragas",
    "community.cat.técnicas": "Técnicas",
    "community.cat.suelo": "Solo",
    "community.cat.semillas": "Sementes",
    "community.cat.certificación": "Certificação",
    "community.event_type.workshop": "Oficina",
    "community.event_type.field_day": "Dia de campo",
    "community.event_type.course": "Curso",
    "community.event_type.meeting": "Encontro",
    "market.add_cart": "Adicionar",
    "cart.title": "Meu Pedido",
    "cart.empty": "Seu carrinho está vazio",
    "cart.send_order": "Enviar pedido",
    "cart.order_sent": "Pedido enviado!",
    "cart.order_to": "Pedido enviado para",
    "cart.total": "Total estimado",
    "cart.grouped_note": "Os pedidos são agrupados por produtor. Cada produtor receberá seu pedido separadamente.",
    "cart.keep_shopping": "Continuar comprando",
    "cart.send_all": "Enviar todo o pedido",
    "cart.order_whatsapp": "📲 O WhatsApp será aberto para coordenar a entrega com cada produtor.",
    "cart.order_email_sent": "Um email com os detalhes do pedido também será enviado ao produtor.",
    "cart.order_next_steps": "Próximos passos: o produtor confirmará a disponibilidade, e vocês combinarão pagamento e entrega.",
    "nav.services": "Serviços",
    "services.badge": "Soluções integrais",
    "services.title": "Tudo o que você precisa para sua transição agroecológica",
    "services.subtitle": "Bio-insumos, sementes, assistência técnica, financiamento, armazenamento, logística e mais.",
    "services.weather_title": "Clima na sua região",
    "services.humidity": "Umidade",
    "services.wind": "Vento",
    "services.weather_note": "Dados do Open-Meteo. Cadastre-se para previsões personalizadas.",
    "services.inputs_title": "Insumos e Sementes",
    "services.inputs_desc": "Acesse bio-insumos e sementes agroecológicas",
    "services.bio_inputs": "Bio-insumos",
    "services.bio_inputs_desc": "Diretório de fornecedores de fertilizantes orgânicos e controladores biológicos.",
    "services.seed_bank": "Banco de Sementes",
    "services.seed_bank_desc": "Troca e venda de sementes nativas e adaptadas localmente.",
    "services.knowledge_title": "Assistência Técnica",
    "services.knowledge_desc": "Conhecimento e assessoria para sua produção",
    "services.library": "Biblioteca Agroecológica",
    "services.library_desc": "Guias, manuais, vídeos e fichas técnicas sobre manejo agroecológico.",
    "services.advisory": "Assessoria Técnica",
    "services.advisory_desc": "Conecte-se com técnicos especializados em produção agroecológica.",
    "services.finance_title": "Financiamento e Programas",
    "services.finance_desc": "Capital, seguros e programas governamentais",
    "services.microcredit": "Microcrédito",
    "services.microcredit_desc": "Acesso a financiamento de baixo custo via cooperativas e programas estatais.",
    "services.insurance": "Seguro Agrícola",
    "services.insurance_desc": "Informações sobre seguros multirriscos disponíveis.",
    "services.gov_programs": "Programas Governamentais",
    "services.gov_programs_desc": "Diretório de programas de apoio à agricultura familiar.",
    "services.available_programs": "Programas disponíveis",
    "services.prog_prohuerta": "Sementes, capacitação e assistência técnica.",
    "services.prog_senasa": "Registro de operadores orgânicos.",
    "services.prog_saf": "Programas de apoio à agricultura familiar.",
    "services.prog_monotributo": "Regime tributário simplificado para a economia social.",
    "services.postharvest_title": "Logística e Pós-colheita",
    "services.postharvest_desc": "Armazenamento, processamento e distribuição",
    "services.storage": "Armazenamento Compartilhado",
    "services.storage_desc": "Encontre centros de coleta e câmaras frias perto de você.",
    "services.processing": "Valor Agregado",
    "services.processing_desc": "Conecte-se com plantas de processamento e cozinhas comunitárias.",
    "services.logistics": "Logística Colaborativa",
    "services.logistics_desc": "Rotas compartilhadas e pontos de distribuição para reduzir custos.",
    "services.view_on_map": "Ver no mapa",
    "services.also_explore": "Explore também estas seções:",
    // Partners
    "partners.badge": "Alianças institucionais",
    "partners.title": "Nos acompanham",
    "partners.subtitle": "Redes, instituições e organizações que acompanham o desenvolvimento da plataforma.",
    "partners.placeholder": "Próximo aliado",
    "partners.cta_title": "Sua instituição ou rede quer se juntar?",
    "partners.cta_text": "Se você representa uma universidade, organismo de pesquisa, organização da sociedade civil ou rede agroecológica, entre em contato para explorar uma colaboração.",
    "partners.cta_button": "Fale conosco",
  },
};

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
  langs: { value: Lang; label: string; flag: string }[];
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Lang>(() => {
    const saved = localStorage.getItem("agrored-lang") as Lang | null;
    return saved && translations[saved] ? saved : "es";
  });

  const changeLang = (l: Lang) => {
    setLang(l);
    localStorage.setItem("agrored-lang", l);
  };

  const t = (key: string): string => translations[lang][key] || translations.es[key] || key;

  const langs = (Object.keys(langLabels) as Lang[]).map((l) => ({
    value: l,
    label: langLabels[l],
    flag: langFlags[l],
  }));

  return (
    <LanguageContext.Provider value={{ lang, setLang: changeLang, t, langs }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};
